### PR TITLE
Don't serve movies with their original file names

### LINKED ISSUE #5: Movie URLs are guessable
Movie URLs are guessable, allowing circumvention of access control to some degree.
I'd suggest making files available via a random URL and sending a `Content-Disposition` header with the original filename.

### PR DESCRIPTION
**Pull request by Eijebong**
This uses a newly assigned UUID on movies as a "secret" to access a
movie file. This avoid leaking movies to unauthenticated people since
they could try guessing filenames (see https://github.com/ArnaudLevaufre/Cinema/issues/5).

To avoid serving movies through django, we set the `X-Accel-Redirect`
header to what nginx calls an internal route. That means that the route
cannot only be served to nginx itself. More info on that here:
https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/

When presented with that header, nginx will ignore the rest of the
response and instead serve what's behind the specified URI. Doing it
this way allows us to keep supporting sending movies through django
(very useful for dev purposes) and keep supporting instances that want
those URLs to not be masked.

Using django's `serve` function sets all the proper headers
so the downloaded file gets its original name.

Note that the route to get a movie is still unauthenticated because
that's useful if you want to use an external viewer like mpv or VLC.

Fixes #5

### CODE REVIEW

**Comment by ArnaudLevaufre** [comment]
Hello Eijebong, it looks good to me even though is seems to be specific to nginx. However I have a question about accessing the movie with unmasked url: 

> keep supporting instances that want those URLs to not be masked.

I don't see how this is achieved in a practical way, since:
- the video source is set to `movie.path_to_static` which build the url with the uuid. 
- the application is no longer serving the media root
- nginx is limiting access to `/media/film`s with the use of the `internal` directive

Am I missing something ?

**Comment by ArnaudLevaufre** [comment]
Hello Eijebong, it looks good to me even though is seems to be specific to nginx. However I have a question about accessing the movie with unmasked url: 

> keep supporting instances that want those URLs to not be masked.

I don't see how this is achieved in a practical way, since:
- the video source is set to `movie.path_to_static` which build the url with the uuid. 
- the application is no longer serving the media root
- nginx is limiting access to `/media/film`s with the use of the `internal` directive

Am I missing something ?

**Comment by Eijebong** [comment]
Well, it's `masked` as in someone running the script from #5 would be able to access movies, not in a practical way. And you're right that the `/media/films` route would be hidden but if you wanted that to be open, it's a one line change.

**Comment by ArnaudLevaufre** [comment]
Okay, that's good for me. Thank you for the contribution.

**Pull request merged**
